{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "from dfa import DFA\n",
    "\n",
    "import networkx as nx\n",
    "import matplotlib.pyplot as plt\n",
    "\n",
    "%matplotlib inline"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Input Graph Format\n",
    "1. Space separated list of states. ($Q$)\n",
    "2. Space separated list of terminals. ($\\sum$)\n",
    "3. Start state. ($q_{0}$)\n",
    "4. Space separated list of final states. ($F$)\n",
    "5. N lines of 3 space separated symbols $A$, $b$ and $C$ representing transition $A \\xrightarrow[b]{} C$. ($\\delta$)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "1 2 3 4 5\r\n",
      "a b\r\n",
      "1\r\n",
      "1 5\r\n",
      "1 a 3\r\n",
      "1 b 2\r\n",
      "2 b 1\r\n",
      "2 a 4\r\n",
      "3 b 4\r\n",
      "3 a 5\r\n",
      "4 a 4\r\n",
      "4 b 4\r\n",
      "5 a 3\r\n",
      "5 b 2\r\n"
     ]
    }
   ],
   "source": [
    "# input graph\n",
    "!cat graph"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "image/svg+xml": [
       "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?>\n",
       "<!DOCTYPE svg PUBLIC \"-//W3C//DTD SVG 1.1//EN\"\n",
       " \"http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd\">\n",
       "<!-- Generated by graphviz version 2.40.1 (20161225.0304)\n",
       " -->\n",
       "<!-- Pages: 1 -->\n",
       "<svg width=\"152pt\" height=\"408pt\"\n",
       " viewBox=\"0.00 0.00 152.00 408.00\" xmlns=\"http://www.w3.org/2000/svg\" xmlns:xlink=\"http://www.w3.org/1999/xlink\">\n",
       "<g id=\"graph0\" class=\"graph\" transform=\"scale(1 1) rotate(0) translate(4 404)\">\n",
       "<polygon fill=\"#ffffff\" stroke=\"transparent\" points=\"-4,4 -4,-404 148,-404 148,4 -4,4\"/>\n",
       "<!-- 1 -->\n",
       "<g id=\"node1\" class=\"node\">\n",
       "<title>1</title>\n",
       "<ellipse fill=\"#c0c0c0\" stroke=\"#000000\" cx=\"102\" cy=\"-378\" rx=\"18\" ry=\"18\"/>\n",
       "<ellipse fill=\"none\" stroke=\"#000000\" cx=\"102\" cy=\"-378\" rx=\"22\" ry=\"22\"/>\n",
       "<text text-anchor=\"middle\" x=\"102\" y=\"-374.3\" font-family=\"Times,serif\" font-size=\"14.00\" fill=\"#000000\">1</text>\n",
       "</g>\n",
       "<!-- 2 -->\n",
       "<g id=\"node2\" class=\"node\">\n",
       "<title>2</title>\n",
       "<ellipse fill=\"#ffffff\" stroke=\"#000000\" cx=\"77\" cy=\"-105\" rx=\"18\" ry=\"18\"/>\n",
       "<text text-anchor=\"middle\" x=\"77\" y=\"-101.3\" font-family=\"Times,serif\" font-size=\"14.00\" fill=\"#000000\">2</text>\n",
       "</g>\n",
       "<!-- 1&#45;&gt;2 -->\n",
       "<g id=\"edge1\" class=\"edge\">\n",
       "<title>1&#45;&gt;2</title>\n",
       "<path fill=\"none\" stroke=\"#000000\" d=\"M110.6262,-357.5901C112.8309,-351.41 114.8906,-344.5282 116,-338 130.6694,-251.6821 151.1162,-221.2049 116,-141 112.6219,-133.2845 106.6841,-126.4891 100.4451,-120.9405\"/>\n",
       "<polygon fill=\"#000000\" stroke=\"#000000\" points=\"102.5406,-118.1344 92.5514,-114.6035 98.1584,-123.593 102.5406,-118.1344\"/>\n",
       "<text text-anchor=\"middle\" x=\"139\" y=\"-239.8\" font-family=\"Times,serif\" font-size=\"14.00\" fill=\"#000000\">b</text>\n",
       "</g>\n",
       "<!-- 3 -->\n",
       "<g id=\"node3\" class=\"node\">\n",
       "<title>3</title>\n",
       "<ellipse fill=\"#ffffff\" stroke=\"#000000\" cx=\"47\" cy=\"-287\" rx=\"18\" ry=\"18\"/>\n",
       "<text text-anchor=\"middle\" x=\"47\" y=\"-283.3\" font-family=\"Times,serif\" font-size=\"14.00\" fill=\"#000000\">3</text>\n",
       "</g>\n",
       "<!-- 1&#45;&gt;3 -->\n",
       "<g id=\"edge2\" class=\"edge\">\n",
       "<title>1&#45;&gt;3</title>\n",
       "<path fill=\"none\" stroke=\"#000000\" d=\"M90.604,-359.1447C82.2138,-345.2628 70.7356,-326.2716 61.6618,-311.2586\"/>\n",
       "<polygon fill=\"#000000\" stroke=\"#000000\" points=\"64.5399,-309.2541 56.3719,-302.5062 58.5491,-312.8749 64.5399,-309.2541\"/>\n",
       "<text text-anchor=\"middle\" x=\"82.5\" y=\"-326.8\" font-family=\"Times,serif\" font-size=\"14.00\" fill=\"#000000\">a</text>\n",
       "</g>\n",
       "<!-- 2&#45;&gt;1 -->\n",
       "<g id=\"edge3\" class=\"edge\">\n",
       "<title>2&#45;&gt;1</title>\n",
       "<path fill=\"none\" stroke=\"#000000\" d=\"M79.0726,-122.9369C79.7174,-128.702 80.4127,-135.1181 81,-141 88.2948,-214.06 95.5837,-299.9219 99.358,-345.5857\"/>\n",
       "<polygon fill=\"#000000\" stroke=\"#000000\" points=\"95.8873,-346.0867 100.1962,-355.7657 102.8637,-345.5122 95.8873,-346.0867\"/>\n",
       "<text text-anchor=\"middle\" x=\"96\" y=\"-239.8\" font-family=\"Times,serif\" font-size=\"14.00\" fill=\"#000000\">b</text>\n",
       "</g>\n",
       "<!-- 4 -->\n",
       "<g id=\"node4\" class=\"node\">\n",
       "<title>4</title>\n",
       "<ellipse fill=\"#ffffff\" stroke=\"#000000\" cx=\"18\" cy=\"-18\" rx=\"18\" ry=\"18\"/>\n",
       "<text text-anchor=\"middle\" x=\"18\" y=\"-14.3\" font-family=\"Times,serif\" font-size=\"14.00\" fill=\"#000000\">4</text>\n",
       "</g>\n",
       "<!-- 2&#45;&gt;4 -->\n",
       "<g id=\"edge4\" class=\"edge\">\n",
       "<title>2&#45;&gt;4</title>\n",
       "<path fill=\"none\" stroke=\"#000000\" d=\"M66.723,-89.8458C57.6706,-76.4973 44.3407,-56.8414 33.9108,-41.4617\"/>\n",
       "<polygon fill=\"#000000\" stroke=\"#000000\" points=\"36.6687,-39.2925 28.1592,-32.9806 30.8753,-43.2214 36.6687,-39.2925\"/>\n",
       "<text text-anchor=\"middle\" x=\"56.5\" y=\"-57.8\" font-family=\"Times,serif\" font-size=\"14.00\" fill=\"#000000\">a</text>\n",
       "</g>\n",
       "<!-- 3&#45;&gt;4 -->\n",
       "<g id=\"edge5\" class=\"edge\">\n",
       "<title>3&#45;&gt;4</title>\n",
       "<path fill=\"none\" stroke=\"#000000\" d=\"M39.0357,-270.7351C32.7827,-257.0392 24.5588,-236.7391 21,-218 9.5403,-157.6581 12.4836,-85.2276 15.398,-46.2167\"/>\n",
       "<polygon fill=\"#000000\" stroke=\"#000000\" points=\"18.8957,-46.3857 16.2073,-36.1376 11.9181,-45.8254 18.8957,-46.3857\"/>\n",
       "<text text-anchor=\"middle\" x=\"19\" y=\"-144.8\" font-family=\"Times,serif\" font-size=\"14.00\" fill=\"#000000\">b</text>\n",
       "</g>\n",
       "<!-- 5 -->\n",
       "<g id=\"node5\" class=\"node\">\n",
       "<title>5</title>\n",
       "<ellipse fill=\"#ffffff\" stroke=\"#000000\" cx=\"52\" cy=\"-196\" rx=\"18\" ry=\"18\"/>\n",
       "<ellipse fill=\"none\" stroke=\"#000000\" cx=\"52\" cy=\"-196\" rx=\"22\" ry=\"22\"/>\n",
       "<text text-anchor=\"middle\" x=\"52\" y=\"-192.3\" font-family=\"Times,serif\" font-size=\"14.00\" fill=\"#000000\">5</text>\n",
       "</g>\n",
       "<!-- 3&#45;&gt;5 -->\n",
       "<g id=\"edge6\" class=\"edge\">\n",
       "<title>3&#45;&gt;5</title>\n",
       "<path fill=\"none\" stroke=\"#000000\" d=\"M47.9878,-269.0213C48.6274,-257.3815 49.4784,-241.8926 50.2321,-228.1757\"/>\n",
       "<polygon fill=\"#000000\" stroke=\"#000000\" points=\"53.7304,-228.3017 50.7844,-218.1248 46.7409,-227.9176 53.7304,-228.3017\"/>\n",
       "<text text-anchor=\"middle\" x=\"54.5\" y=\"-239.8\" font-family=\"Times,serif\" font-size=\"14.00\" fill=\"#000000\">a</text>\n",
       "</g>\n",
       "<!-- 4&#45;&gt;4 -->\n",
       "<g id=\"edge7\" class=\"edge\">\n",
       "<title>4&#45;&gt;4</title>\n",
       "<path fill=\"none\" stroke=\"#000000\" d=\"M34.6641,-25.3828C44.625,-27.0234 54,-24.5625 54,-18 54,-13.7959 50.1525,-11.2751 44.7682,-10.4375\"/>\n",
       "<polygon fill=\"#000000\" stroke=\"#000000\" points=\"44.6002,-6.9399 34.6641,-10.6172 44.7247,-13.9388 44.6002,-6.9399\"/>\n",
       "<text text-anchor=\"middle\" x=\"65\" y=\"-14.3\" font-family=\"Times,serif\" font-size=\"14.00\" fill=\"#000000\">a,b</text>\n",
       "</g>\n",
       "<!-- 5&#45;&gt;2 -->\n",
       "<g id=\"edge8\" class=\"edge\">\n",
       "<title>5&#45;&gt;2</title>\n",
       "<path fill=\"none\" stroke=\"#000000\" d=\"M57.9247,-174.4343C61.3995,-161.7857 65.8221,-145.6875 69.5338,-132.177\"/>\n",
       "<polygon fill=\"#000000\" stroke=\"#000000\" points=\"72.9319,-133.0198 72.2061,-122.4498 66.182,-131.1653 72.9319,-133.0198\"/>\n",
       "<text text-anchor=\"middle\" x=\"72\" y=\"-144.8\" font-family=\"Times,serif\" font-size=\"14.00\" fill=\"#000000\">b</text>\n",
       "</g>\n",
       "<!-- 5&#45;&gt;3 -->\n",
       "<g id=\"edge9\" class=\"edge\">\n",
       "<title>5&#45;&gt;3</title>\n",
       "<path fill=\"none\" stroke=\"#000000\" d=\"M43.3738,-216.4099C41.1691,-222.59 39.1094,-229.4718 38,-236 36.6744,-243.8002 37.3236,-252.2642 38.7466,-260.0138\"/>\n",
       "<polygon fill=\"#000000\" stroke=\"#000000\" points=\"35.3943,-261.0528 41.0539,-270.0093 42.215,-259.4783 35.3943,-261.0528\"/>\n",
       "<text text-anchor=\"middle\" x=\"42.5\" y=\"-239.8\" font-family=\"Times,serif\" font-size=\"14.00\" fill=\"#000000\">a</text>\n",
       "</g>\n",
       "</g>\n",
       "</svg>\n"
      ],
      "text/plain": [
       "<graphviz.files.Source at 0x7f5e55883fd0>"
      ]
     },
     "execution_count": 3,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# initialize DFA from file\n",
    "filename = 'graph'\n",
    "dfa = DFA(filename)\n",
    "dfa.draw()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "4 states. 1 final states. start state - 3\n"
     ]
    }
   ],
   "source": [
    "# minimize dfa\n",
    "dfa.minimize()\n",
    "print(dfa)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "image/svg+xml": [
       "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?>\n",
       "<!DOCTYPE svg PUBLIC \"-//W3C//DTD SVG 1.1//EN\"\n",
       " \"http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd\">\n",
       "<!-- Generated by graphviz version 2.40.1 (20161225.0304)\n",
       " -->\n",
       "<!-- Pages: 1 -->\n",
       "<svg width=\"89pt\" height=\"313pt\"\n",
       " viewBox=\"0.00 0.00 89.00 313.00\" xmlns=\"http://www.w3.org/2000/svg\" xmlns:xlink=\"http://www.w3.org/1999/xlink\">\n",
       "<g id=\"graph0\" class=\"graph\" transform=\"scale(1 1) rotate(0) translate(4 309)\">\n",
       "<polygon fill=\"#ffffff\" stroke=\"transparent\" points=\"-4,4 -4,-309 85,-309 85,4 -4,4\"/>\n",
       "<!-- 1 -->\n",
       "<g id=\"node1\" class=\"node\">\n",
       "<title>1</title>\n",
       "<ellipse fill=\"#ffffff\" stroke=\"#000000\" cx=\"35\" cy=\"-287\" rx=\"18\" ry=\"18\"/>\n",
       "<text text-anchor=\"middle\" x=\"35\" y=\"-283.3\" font-family=\"Times,serif\" font-size=\"14.00\" fill=\"#000000\">1</text>\n",
       "</g>\n",
       "<!-- 2 -->\n",
       "<g id=\"node2\" class=\"node\">\n",
       "<title>2</title>\n",
       "<ellipse fill=\"#ffffff\" stroke=\"#000000\" cx=\"18\" cy=\"-18\" rx=\"18\" ry=\"18\"/>\n",
       "<text text-anchor=\"middle\" x=\"18\" y=\"-14.3\" font-family=\"Times,serif\" font-size=\"14.00\" fill=\"#000000\">2</text>\n",
       "</g>\n",
       "<!-- 1&#45;&gt;2 -->\n",
       "<g id=\"edge1\" class=\"edge\">\n",
       "<title>1&#45;&gt;2</title>\n",
       "<path fill=\"none\" stroke=\"#000000\" d=\"M31.6452,-269.1058C30.6648,-263.3431 29.6762,-256.9175 29,-251 20.6074,-177.5593 18.5906,-90.3927 18.1242,-46.41\"/>\n",
       "<polygon fill=\"#000000\" stroke=\"#000000\" points=\"21.6223,-46.1624 18.0361,-36.193 14.6226,-46.2229 21.6223,-46.1624\"/>\n",
       "<text text-anchor=\"middle\" x=\"25.5\" y=\"-144.8\" font-family=\"Times,serif\" font-size=\"14.00\" fill=\"#000000\">a</text>\n",
       "</g>\n",
       "<!-- 3 -->\n",
       "<g id=\"node3\" class=\"node\">\n",
       "<title>3</title>\n",
       "<ellipse fill=\"#c0c0c0\" stroke=\"#000000\" cx=\"59\" cy=\"-196\" rx=\"18\" ry=\"18\"/>\n",
       "<ellipse fill=\"none\" stroke=\"#000000\" cx=\"59\" cy=\"-196\" rx=\"22\" ry=\"22\"/>\n",
       "<text text-anchor=\"middle\" x=\"59\" y=\"-192.3\" font-family=\"Times,serif\" font-size=\"14.00\" fill=\"#000000\">3</text>\n",
       "</g>\n",
       "<!-- 1&#45;&gt;3 -->\n",
       "<g id=\"edge2\" class=\"edge\">\n",
       "<title>1&#45;&gt;3</title>\n",
       "<path fill=\"none\" stroke=\"#000000\" d=\"M33.1811,-268.7448C32.7369,-258.8776 33.0633,-246.5813 36,-236 37.2137,-231.6268 39.0167,-227.2301 41.0888,-223.0345\"/>\n",
       "<polygon fill=\"#000000\" stroke=\"#000000\" points=\"44.1646,-224.7048 45.9302,-214.2581 38.0353,-221.3236 44.1646,-224.7048\"/>\n",
       "<text text-anchor=\"middle\" x=\"41\" y=\"-239.8\" font-family=\"Times,serif\" font-size=\"14.00\" fill=\"#000000\">b</text>\n",
       "</g>\n",
       "<!-- 2&#45;&gt;2 -->\n",
       "<g id=\"edge3\" class=\"edge\">\n",
       "<title>2&#45;&gt;2</title>\n",
       "<path fill=\"none\" stroke=\"#000000\" d=\"M34.6641,-25.3828C44.625,-27.0234 54,-24.5625 54,-18 54,-13.7959 50.1525,-11.2751 44.7682,-10.4375\"/>\n",
       "<polygon fill=\"#000000\" stroke=\"#000000\" points=\"44.6002,-6.9399 34.6641,-10.6172 44.7247,-13.9388 44.6002,-6.9399\"/>\n",
       "<text text-anchor=\"middle\" x=\"65\" y=\"-14.3\" font-family=\"Times,serif\" font-size=\"14.00\" fill=\"#000000\">a,b</text>\n",
       "</g>\n",
       "<!-- 3&#45;&gt;1 -->\n",
       "<g id=\"edge4\" class=\"edge\">\n",
       "<title>3&#45;&gt;1</title>\n",
       "<path fill=\"none\" stroke=\"#000000\" d=\"M54.2565,-217.4988C51.9215,-227.691 48.9735,-240.0137 46,-251 45.1895,-253.9945 44.3014,-257.1162 43.3923,-260.215\"/>\n",
       "<polygon fill=\"#000000\" stroke=\"#000000\" points=\"40.0224,-259.2677 40.4861,-269.8524 46.7243,-261.2888 40.0224,-259.2677\"/>\n",
       "<text text-anchor=\"middle\" x=\"54\" y=\"-239.8\" font-family=\"Times,serif\" font-size=\"14.00\" fill=\"#000000\">b</text>\n",
       "</g>\n",
       "<!-- 4 -->\n",
       "<g id=\"node4\" class=\"node\">\n",
       "<title>4</title>\n",
       "<ellipse fill=\"#ffffff\" stroke=\"#000000\" cx=\"48\" cy=\"-105\" rx=\"18\" ry=\"18\"/>\n",
       "<text text-anchor=\"middle\" x=\"48\" y=\"-101.3\" font-family=\"Times,serif\" font-size=\"14.00\" fill=\"#000000\">4</text>\n",
       "</g>\n",
       "<!-- 3&#45;&gt;4 -->\n",
       "<g id=\"edge5\" class=\"edge\">\n",
       "<title>3&#45;&gt;4</title>\n",
       "<path fill=\"none\" stroke=\"#000000\" d=\"M48.7145,-176.1599C45.9707,-169.8814 43.3855,-162.8023 42,-156 40.4586,-148.4326 40.6474,-140.1469 41.5719,-132.4956\"/>\n",
       "<polygon fill=\"#000000\" stroke=\"#000000\" points=\"45.0332,-133.0164 43.1952,-122.5822 38.1252,-131.8852 45.0332,-133.0164\"/>\n",
       "<text text-anchor=\"middle\" x=\"46.5\" y=\"-144.8\" font-family=\"Times,serif\" font-size=\"14.00\" fill=\"#000000\">a</text>\n",
       "</g>\n",
       "<!-- 4&#45;&gt;2 -->\n",
       "<g id=\"edge6\" class=\"edge\">\n",
       "<title>4&#45;&gt;2</title>\n",
       "<path fill=\"none\" stroke=\"#000000\" d=\"M42.073,-87.8116C37.8408,-75.5383 32.0651,-58.7887 27.2319,-44.7725\"/>\n",
       "<polygon fill=\"#000000\" stroke=\"#000000\" points=\"30.4835,-43.4654 23.9147,-35.1527 23.8659,-45.7474 30.4835,-43.4654\"/>\n",
       "<text text-anchor=\"middle\" x=\"39\" y=\"-57.8\" font-family=\"Times,serif\" font-size=\"14.00\" fill=\"#000000\">b</text>\n",
       "</g>\n",
       "<!-- 4&#45;&gt;3 -->\n",
       "<g id=\"edge7\" class=\"edge\">\n",
       "<title>4&#45;&gt;3</title>\n",
       "<path fill=\"none\" stroke=\"#000000\" d=\"M50.1946,-123.1556C51.6035,-134.8111 53.4725,-150.2722 55.126,-163.9511\"/>\n",
       "<polygon fill=\"#000000\" stroke=\"#000000\" points=\"51.6624,-164.4638 56.3372,-173.9714 58.6118,-163.6237 51.6624,-164.4638\"/>\n",
       "<text text-anchor=\"middle\" x=\"58.5\" y=\"-144.8\" font-family=\"Times,serif\" font-size=\"14.00\" fill=\"#000000\">a</text>\n",
       "</g>\n",
       "</g>\n",
       "</svg>\n"
      ],
      "text/plain": [
       "<graphviz.files.Source at 0x7f5e5500c0b8>"
      ]
     },
     "execution_count": 5,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# draw minimized dfa\n",
    "dfa.draw()"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.6.4"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
